### ISSUE TITLE
Cannot reproduce result on ObstructedMaze-Full

### ISSUE THREAD

**Issue by sungwoong** [yfletberliac/adversarially-guided-actor-critic#2]
Hi @yfletberliac 

I ran your codes for the environment of "ObstructedMaze-Full" with the default config file (minigrid.yaml).
However, the average return was not increased even after 100M steps, which is different from your result in Fig.8 of your paper.
Could you check it or share your log?

My obtained plots are as follows. Here, the orange curve is MultiRoom-N10-S10, and the green curve is ObstructedMaze-Full.

Thanks,
Sungwoong.

![Screen Shot 2022-02-10 at 5 41 01 PM](https://user-images.githubusercontent.com/39327337/153370865-c7114434-ad61-45c6-bccd-463d3e5131fd.png)
![Screen Shot 2022-02-10 at 5 41 16 PM](https://user-images.githubusercontent.com/39327337/153370882-a0e546e1-2c3e-4695-b83a-b9f6668fd6a2.png)
![Screen Shot 2022-02-10 at 5 41 31 PM](https://user-images.githubusercontent.com/39327337/153370901-1da3c5dc-0d22-4879-bdb6-37cb0dbbcaab.png)
![Screen Shot 2022-02-10 at 5 42 00 PM](https://user-images.githubusercontent.com/39327337/153370914-df24c6d6-3e16-47d8-a454-36cf5a787164.png)

**Comment by yfletberliac** [comment]
Hello @sungwoong,

Thanks for your comment. Just to confirm from the fact that you are using the `minigrid.yaml` file: are you referring to the PyTorch implementation? This is an external version that has not been fine-tuned to reproduce all experiments in the paper.

I would advise choosing one of the two following solutions: either using the original TensorFlow implementation which should reproduce all results out-of-the-box, or proceed with fine-tuning the PyTorch implementation on the ObstructedMaze tasks, which I understand can be time-consuming to do. I'm happy to assist in either case.

Best,
Yannis

**Comment by sungwoong** [comment]
Hi @yfletberliac

Thanks for your reply.
Yes, I ran the pytorch codes with minigrid.yaml.
As you suggested, I will run your tf codes while can you recheck the hyperparameters in the pytorch implementation? 
I just fount that "episodic_count_coeff" seems to be different as
- in agac.py (TF)
    - mb_rewards = mb_rewards + mb_state_count * 0.1
- minigrid.yaml (pytorch)
    - "episodic_count_coefficient": 0.0125

Thanks,
Sungwoong.

**Comment by yfletberliac** [comment]
Hi @sungwoong, thanks for getting back to me.

> - in agac.py (TF)
>   - mb_rewards = mb_rewards + mb_state_count * 0.1
> - minigrid.yaml (pytorch)
>   - "episodic_count_coefficient": 0.0125

You're right - and the episodic count coefficient is an important HP for those harder environments. In the PyTorch version, please try setting the `episodic_count_coefficient` higher to 0.1. The network sizes are also different with the original TF implementation, but overall less critical than `episodic_count_coefficient`.

**Comment by sungwoong** [comment]
Hi @yfletberliac 

- I re-run the pytorch codes with 0.1 of episodic_count_coefficient , but the score is still 0 at 50M steps.
- I also tried to run the tf codes but got the following error.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(256, 32), b.shape=(32, 256), m=256, n=256, k=32
         [[{{node train_model/model/fc1_pi/MatMul}}]]
  (1) Internal: Blas GEMM launch failed : a.shape=(256, 32), b.shape=(32, 256), m=256, n=256, k=32
         [[{{node train_model/model/fc1_pi/MatMul}}]]
         [[loss/Mean_4/_131]]
0 successful operations.
0 derived errors ignored.
```
- It seems that there is no difference in network sizes between the pytorch and tf codes, except the kind of non-linear activation in MLP layers.

**Comment by yfletberliac** [comment]
Hello @sungwoong,

1/ I haven't extensively used the PyTorch version, but one debugging/fine-tuning approach would be to plot the adversarial bonus and episodic-count return to understand what's going on under the hood.

2/ Have you tried using this
```
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU') 
for device in physical_devices:
    tf.config.experimental.set_memory_growth(device, True)
```
 per https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth

Have you used https://github.com/yfletberliac/adversarially-guided-actor-critic/blob/main/requirements.txt to set up your virtual env? I recommend using TF version 1.14.0 for minimum trouble.

**Comment by yfletberliac** [comment]
Hi @sungwoong,

Checking in on this, have you had a chance to look further into the TF version?
